[versions]
kotlin = "2.0.21"
agp = "8.7.1"
hilt = "1.3.0"
daggerHilt = "2.53.1"
kotlinx = "1.7.3"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
navigationCompose = "2.9.1"
composeBom = "2024.08.00"
accompanistPermissions = "0.37.3"
room = "2.8.4"
coil = "2.7.0"
materialIcons = "1.6.8"
wheelPicker = "1.1.11"
zxing = "3.5.1"
firebaseBom = "34.1.0"
androidxCredentials = "1.5.0"
googleid = "1.1.1"
splashscreen = "1.0.1"
media3 = "1.8.0"
shimmer = "1.3.3"
haze = "1.6.10"
datastore = "1.1.7"
workRuntimeKtx = "2.11.1"
accompanistSystemUiController = "0.36.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
dagger-hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "daggerHilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material-icons = { group = "androidx.compose.material", name = "material-icons-extended-android", version.ref = "materialIcons" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

dagger-hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerHilt" }
dagger-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "daggerHilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerHilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hilt" }
hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hilt" }

coil-core = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
wheelPicker-compose = { group = "com.github.commandiron", name = "WheelPickerCompose", version.ref = "wheelPicker" }
google-identity = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name="firebase-firestore" }

androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidxCredentials" }
androidx-credentials-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidxCredentials" }

androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }

splashscreen = { group = "androidx.core", name="core-splashscreen", version.ref="splashscreen"}

androidx-media3-exoplayer = { group = "androidx.media3", name="media3-exoplayer", version.ref="media3"}
androidx-media3-session = { group = "androidx.media3", name="media3-session", version.ref="media3"}
androidx-media3-datasource-cronet = { group = "androidx.media3", name="media3-datasource-cronet", version.ref="media3"}
androidx-media3-ui = { group = "androidx.media3", name="media3-ui", version.ref="media3"}
androidx-media3-common = { group = "androidx.media3", name="media3-common", version.ref="media3"}
androidx-media3-common-ktx = { group = "androidx.media3", name="media3-common-ktx", version.ref="media3"}

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name="kotlinx-serialization-json", version.ref="kotlinx"}

shimmer-compose = { group = "com.valentinilk.shimmer", name="compose-shimmer", version.ref="shimmer"}
haze-compose = { group = "dev.chrisbanes.haze", name="haze", version.ref="haze" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name="accompanist-systemuicontroller", version.ref="accompanistSystemUiController" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

